### ISSUE TITLE
Why does the bat packet depend on less?

### ISSUE THREAD

**Issue by Drllap** [rasmuskriest/Chocolatey-Packages#8]
Is this still valid?
https://github.com/rasmuskriest/Chocolatey-Packages/blob/8484a640d58c94e29a8d613525c564b203aec1a4/bat/bat.nuspec#L24

**Comment by rasmuskriest** [comment]
Hi @Drllap - please refer to https://github.com/sharkdp/bat#paging as to why `bat` depends on `less`.
